### ISSUE TITLE
GraphCool vs Prisma

### ISSUE THREAD

**Issue by davidjohnbell** [graphql-boilerplates/vue-fullstack-graphql#75]
Recently I read [this](https://www.prismagraphql.com/) post about Prisma and found my way to this repository. Your commit history mentions graphcool which has now been turned into Prisma. However, the Prisma website says a Vue boilerplate was coming soon i.e. not ready. Can I use this repository and expect to get a Prisma server?

**Comment by marktani** [comment]
Hey David, this repository is currently not in a working state as mentioned in the README. We're currently looking for a contributor to change that :slightly_smiling_face: Ping me [in our Slack](http://slack.graph.cool) if you'd like to help you out with that! :raised_hands:
